language: ruby

rvm: 2.3.3

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec

before_script:
  - psql -c 'create database ticketee_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  
