language: ruby
rvm: 2.3.3
services:
- postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rspec
before_script:
- psql -c 'create database ticketee_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: oM32Yaa5nY3y9Lq2NLiXD7V3i4Sst3MXgya7jOxfIANWAP1kU5+SH/sn1ZR3uMRRa9uSvnQKruf8LEtcx8Hr8UQUpRgq+un9wTF9l91EQZnaA/vQ+5kJ9cdhkgyfJVnL8nURfIEoztppOwkfUHKq9B5EHt3oO/1c4SUDMfON6Zo8tjdoyTM60oKdk0yp886QqVMafmobsFMQH0Puhxwx2oQZYEV3JLeOMetK+X69k8GL/TG5oDt5fnNzHEx7WOklQcmUGSB2d2pXLYoOkioJcLSc2KmCsBl5/GLPjMTth+RJomFjy2GDzCcEd4/Q2XZybA0vT7IVqv1uOQ3DMyF7IxCvMGVmlLgmvDQbxTwvmBgsdeWpXbdgITyIglQ/oPWmeQx6R3KfdJp9J+JbozVyaGkQgw5FjqV2PB1lYmWcTFHkiAlCOqG+E4nUdkn/Fk9OkeWW9T/izKigPSJM5kKDhUOlLYLLaaPjli5npeWTHsYuDgVN4ykD2Ow3w9sddvJtZh07DEZX8eXt1XCc2lAF2F6GrxsWo1ebtyYQExUot73gU8NV3s5oJ1XEdQg5wy3clgjd+syYTw4qtcL3nnqpBoHbCAYtryLfSfdPghZr3ncLFahQaWxwYNxXb+bSeCqU5OxQONZSLEfB1MeiWGCuFambM+5tpFRSWC3OJkShFtw=
  app: damp-river-43120
  on:
    repo: amandeep511997/ticketee
